# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-gke-cluster-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-gke-cluster
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-gke-cluster.git
      sourceType: git
  ui:
    input:
      variables:
        additional_networks:
          name: additional_networks
          title: Additional Networks
        authenticator_security_group:
          name: authenticator_security_group
          title: Authenticator Security Group
        authorized_cidr:
          name: authorized_cidr
          title: Authorized Cidr
        autoscaling_profile:
          name: autoscaling_profile
          title: Autoscaling Profile
        configure_workload_identity_sa:
          name: configure_workload_identity_sa
          title: Configure Workload Identity Sa
        deployment_name:
          name: deployment_name
          title: Deployment Name
        enable_dataplane_v2:
          name: enable_dataplane_v2
          title: Enable Dataplane V2
        enable_filestore_csi:
          name: enable_filestore_csi
          title: Enable Filestore Csi
        enable_gcsfuse_csi:
          name: enable_gcsfuse_csi
          title: Enable Gcsfuse Csi
        enable_master_global_access:
          name: enable_master_global_access
          title: Enable Master Global Access
        enable_multi_networking:
          name: enable_multi_networking
          title: Enable Multi Networking
        enable_parallelstore_csi:
          name: enable_parallelstore_csi
          title: Enable Parallelstore Csi
        enable_persistent_disk_csi:
          name: enable_persistent_disk_csi
          title: Enable Persistent Disk Csi
        enable_private_endpoint:
          name: enable_private_endpoint
          title: Enable Private Endpoint
        enable_private_ipv6_google_access:
          name: enable_private_ipv6_google_access
          title: Enable Private Ipv6 Google Access
        enable_private_nodes:
          name: enable_private_nodes
          title: Enable Private Nodes
        gcp_public_cidrs_access_enabled:
          name: gcp_public_cidrs_access_enabled
          title: Gcp Public Cidrs Access Enabled
        labels:
          name: labels
          title: Labels
        maintenance_exclusions:
          name: maintenance_exclusions
          title: Maintenance Exclusions
        maintenance_start_time:
          name: maintenance_start_time
          title: Maintenance Start Time
        master_authorized_networks:
          name: master_authorized_networks
          title: Master Authorized Networks
        master_ipv4_cidr_block:
          name: master_ipv4_cidr_block
          title: Master Ipv4 Cidr Block
        min_master_version:
          name: min_master_version
          title: Min Master Version
        name_suffix:
          name: name_suffix
          title: Name Suffix
        network_id:
          name: network_id
          title: Network Id
        pods_ip_range_name:
          name: pods_ip_range_name
          title: Pods Ip Range Name
        prefix_with_deployment_name:
          name: prefix_with_deployment_name
          title: Prefix With Deployment Name
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
        release_channel:
          name: release_channel
          title: Release Channel
        service_account:
          name: service_account
          title: Service Account
        service_account_email:
          name: service_account_email
          title: Service Account Email
        service_account_scopes:
          name: service_account_scopes
          title: Service Account Scopes
        services_ip_range_name:
          name: services_ip_range_name
          title: Services Ip Range Name
        subnetwork_self_link:
          name: subnetwork_self_link
          title: Subnetwork Self Link
        system_node_pool_enable_secure_boot:
          name: system_node_pool_enable_secure_boot
          title: System Node Pool Enable Secure Boot
        system_node_pool_enabled:
          name: system_node_pool_enabled
          title: System Node Pool Enabled
        system_node_pool_image_type:
          name: system_node_pool_image_type
          title: System Node Pool Image Type
        system_node_pool_kubernetes_labels:
          name: system_node_pool_kubernetes_labels
          title: System Node Pool Kubernetes Labels
        system_node_pool_machine_type:
          name: system_node_pool_machine_type
          title: System Node Pool Machine Type
        system_node_pool_name:
          name: system_node_pool_name
          title: System Node Pool Name
        system_node_pool_node_count:
          name: system_node_pool_node_count
          title: System Node Pool Node Count
        system_node_pool_taints:
          name: system_node_pool_taints
          title: System Node Pool Taints
        timeout_create:
          name: timeout_create
          title: Timeout Create
        timeout_update:
          name: timeout_update
          title: Timeout Update
